language: node_js
node_js:
  - node

git:
  depth: false

sudo: required
dist: trusty
group: edge

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - g++-4.8
      - google-chrome-stable

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome

after_success:
  - npm run coveralls
